# Generated by Django 3.1.14 on 2022-03-25 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='profile_pictures'),
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
